---
# Enable the load balancer tier

- name: enable the load balancer tier
  hosts: frontends
  roles:
    - {name: base-cfg, tags: base-cfg}
    - {name: loadbalancer-tier, tags: [loadbalancer, haproxy]}

# Enable the app tier

- name: setup app tier
  hosts: apps
  gather_facts: false
  roles:
    - {name: base-cfg, tags: base-cfg}
    - {name: application-tier, tags: [application, tomcat]}

# Setup database tier

- name: setup database tier
  hosts: appdbs
  roles:
    - {name: base-cfg, tags: base-cfg}
    - {name: postgres, tags: [db, postgres]}

# Ensure app is working 

- name: app check 
  hosts: frontends
  roles:
    - {name: smoke-test, tags: smoke-test}
