---
- name: Create Windows Domain groups
  win_domain_group:
    name: "{{ item.group }}"
    scope: "{{ item.group_scope }}"
  with_items: "{{ user_info }}"

- name: Create Windows Domain users
  win_domain_user:
    name: "{{ item.name }}"
    firstname: "{{ item.firstname }}"
    surname: "{{ item.surname }}"
    password: "{{ item.password }}"
    email: "{{ item.email }}"
    state: present
  with_items: "{{ user_info }}"
